# Generated by Django 4.0.4 on 2022-04-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0002_alter_mainpage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='description',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='description_under',
            field=models.TextField(blank=True, verbose_name='Описание главной страницы под фотографиями'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='description_upper',
            field=models.TextField(blank=True, verbose_name='Описание главной страницы над фотографиями'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='picture1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фотография на странице'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='picture2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фотография на странице'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='picture3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фотография на странице'),
        ),
    ]
