# Generated by Django 4.0.4 on 2022-05-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0002_alter_masterservice_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterservice',
            name='registration',
        ),
        migrations.AddField(
            model_name='registration',
            name='masterservice',
            field=models.ManyToManyField(blank=True, to='nails.masterservice'),
        ),
    ]
