# Generated by Django 4.0.4 on 2022-04-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0003_remove_mainpage_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя мастера')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото мастера')),
                ('position', models.CharField(max_length=100, verbose_name='Занимаемая должность и стаж')),
                ('rating', models.IntegerField(default=1, verbose_name='Рейтинг мастера')),
                ('description', models.TextField(max_length=500, verbose_name='О мастере')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
    ]
