# Generated by Django 4.0.4 on 2022-05-09 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0003_remove_masterservice_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nails.master', verbose_name='Мастер'),
        ),
    ]
