# Generated by Django 4.0.4 on 2022-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0004_registration_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='service',
            field=models.ManyToManyField(null=True, to='nails.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='masterservice',
            field=models.ManyToManyField(to='nails.masterservice'),
        ),
    ]
