# Generated by Django 4.0.4 on 2022-04-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0005_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='position',
        ),
        migrations.AddField(
            model_name='master',
            name='experience',
            field=models.CharField(max_length=50, null=True, verbose_name='Стаж'),
        ),
        migrations.AddField(
            model_name='master',
            name='grade',
            field=models.CharField(max_length=50, null=True, verbose_name='Занимаемая должность'),
        ),
    ]
