# Generated by Django 4.0.4 on 2022-05-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0005_registration_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='service',
            field=models.ManyToManyField(to='nails.service', verbose_name='Услуга'),
        ),
    ]
