# Generated by Django 4.0.4 on 2022-05-10 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0006_alter_registration_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nails.master', verbose_name='Мастер'),
        ),
    ]
