# Generated by Django 4.0.4 on 2022-04-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0006_remove_master_position_master_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Наименование услуги'),
        ),
        migrations.CreateModel(
            name='MasterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(verbose_name='Продолжительность')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nails.master')),
                ('Services', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nails.service')),
            ],
        ),
    ]
