# Generated by Django 4.0.4 on 2022-04-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0008_alter_masterservice_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterservice',
            options={'verbose_name': 'Продолжительность и цена услуги', 'verbose_name_plural': 'Продолжительность и цена услуги'},
        ),
    ]
