# Generated by Django 4.0.4 on 2022-04-21 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0009_alter_masterservice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.IntegerField(null=True, verbose_name='Продолжительность в минутах'),
        ),
        migrations.AddField(
            model_name='service',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nails.master'),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.DeleteModel(
            name='MasterService',
        ),
    ]
