# Generated by Django 4.0.4 on 2022-04-21 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0010_service_duration_service_master_service_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='service',
            name='master',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.CreateModel(
            name='MasterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(verbose_name='Продолжительность в минутах')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nails.master')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nails.service')),
            ],
            options={
                'verbose_name': 'Продолжительность и цена услуги',
                'verbose_name_plural': 'Продолжительность и цена услуги',
            },
        ),
    ]
