# Generated by Django 4.0.4 on 2022-04-24 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0011_remove_service_duration_remove_service_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterservice',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nails.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='masterservice',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nails.service', verbose_name='Услуга'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('users_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('date_and_time', models.CharField(blank=True, max_length=50)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nails.master')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nails.service')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Запись',
            },
        ),
    ]
