# Generated by Django 4.0.4 on 2022-04-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0012_alter_masterservice_master_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='registration',
            name='reg_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='reg_time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
