# Generated by Django 4.0.4 on 2022-04-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0013_remove_registration_date_and_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='reg_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reg_time',
            field=models.DateField(null=True),
        ),
    ]
