# Generated by Django 4.0.4 on 2022-04-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0014_alter_registration_reg_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='reg_time',
            field=models.TimeField(null=True),
        ),
    ]
