# Generated by Django 4.0.4 on 2022-04-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0015_alter_registration_reg_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='service',
        ),
        migrations.AddField(
            model_name='registration',
            name='service',
            field=models.ManyToManyField(to='nails.service'),
        ),
    ]
