# Generated by Django 4.0.4 on 2022-05-01 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0016_remove_registration_service_registration_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nails.master', verbose_name='Выбор мастера'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reg_date',
            field=models.DateField(null=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reg_time',
            field=models.TimeField(null=True, verbose_name='Время записи'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='service',
            field=models.ManyToManyField(to='nails.service', verbose_name='Выбор услуг'),
        ),
    ]
