# Generated by Django 4.0.4 on 2022-05-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0017_alter_registration_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='service',
            field=models.ManyToManyField(related_name='reg', to='nails.service', verbose_name='Выбор услуг'),
        ),
    ]
